version: "3.9"
services:
  app:
    container_name: c-test-api
    build:
      target: dev-turbo
    volumes:
      - ./:/app
    ports:
      - "7777:80"

  prometheus:
    container_name: c-prometheus
    image: prom/prometheus:latest
    depends_on:
      - app
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-enterprise
    container_name: c-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - '3000:3000'